// Restaurant and menu mock data
export const mockRestaurants = [
  {
    id: "1",
    name: "Pizza Paradise",
    description: "Authentic Italian pizzas and pasta",
    image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3",
    cuisine: ["Italian", "Pizza"],
    rating: 4.5,
    deliveryFee: 0,
    minOrder: 15,
    isOpen: true,
    address: "123 Main St",
    menu: [
      {
        id: "1-1",
        name: "Margherita Pizza",
        description: "Fresh tomatoes, mozzarella, basil",
        price: 14.99,
        category: "Pizza",
        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002",
        available: true,
      },
      {
        id: "1-2",
        name: "Pepperoni Pizza",
        description: "Classic pepperoni with extra cheese",
        price: 16.99,
        category: "Pizza",
        image: "https://images.unsplash.com/photo-1628840042765-356cda07504e",
        available: true,
      },
      {
        id: "1-3",
        name: "Spaghetti Carbonara",
        description: "Creamy pasta with pancetta",
        price: 13.99,
        category: "Pasta",
        image: "https://images.unsplash.com/photo-1612874742237-6526221588e3",
        available: true,
      },
      {
        id: "1-4",
        name: "Garlic Bread",
        description: "Toasted bread with garlic butter",
        price: 4.99,
        category: "Sides",
        image: "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c",
        available: true,
      },
      {
        id: "1-5",
        name: "Tiramisu",
        description: "Classic Italian dessert",
        price: 6.99,
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9",
        available: true,
      },
    ],
  },
  {
    id: "2",
    name: "Sushi Master",
    description: "Premium Japanese cuisine",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c",
    cuisine: ["Japanese", "Sushi"],
    rating: 4.8,
    deliveryFee: 3.5,
    minOrder: 20,
    isOpen: true,
    address: "456 Oak St",
    menu: [
      {
        id: "2-1",
        name: "California Roll",
        description: "Crab, avocado, cucumber",
        price: 12.99,
        category: "Rolls",
        image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351",
        available: true,
      },
      {
        id: "2-2",
        name: "Salmon Nigiri",
        description: "Fresh salmon over rice",
        price: 8.99,
        category: "Nigiri",
        image: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56",
        available: true,
      },
      {
        id: "2-3",
        name: "Tempura Udon",
        description: "Thick noodles in hot broth",
        price: 15.99,
        category: "Noodles",
        image: "https://images.unsplash.com/photo-1618841557871-b4664fb2e94a",
        available: true,
      },
      {
        id: "2-4",
        name: "Miso Soup",
        description: "Traditional Japanese soup",
        price: 3.99,
        category: "Sides",
        image: "https://images.unsplash.com/photo-1607301405390-d831c242d4b6",
        available: true,
      },
      {
        id: "2-5",
        name: "Green Tea Ice Cream",
        description: "Matcha flavored ice cream",
        price: 5.99,
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1505394033641-40c6ad1178d7",
        available: true,
      },
    ],
  },
  {
    id: "3",
    name: "Burger Bliss",
    description: "Gourmet burgers and fries",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add",
    cuisine: ["American", "Burgers"],
    rating: 4.6,
    deliveryFee: 2.5,
    minOrder: 15,
    isOpen: true,
    address: "789 Burger Lane",
    menu: [
      {
        id: "3-1",
        name: "Classic Cheeseburger",
        description: "Beef patty with cheddar",
        price: 11.99,
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
        available: true,
      },
      {
        id: "3-2",
        name: "Bacon Deluxe",
        description: "Burger with bacon and avocado",
        price: 14.99,
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5",
        available: true,
      },
      {
        id: "3-3",
        name: "Truffle Fries",
        description: "With parmesan and herbs",
        price: 6.99,
        category: "Sides",
        image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877",
        available: true,
      },
      {
        id: "3-4",
        name: "Onion Rings",
        description: "Crispy battered onion rings",
        price: 5.99,
        category: "Sides",
        image: "https://images.unsplash.com/photo-1639024471283-03518883512d",
        available: true,
      },
      {
        id: "3-5",
        name: "Milkshake",
        description: "Choice of vanilla, chocolate, or strawberry",
        price: 6.99,
        category: "Drinks",
        image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699",
        available: true,
      },
    ],
  },
  {
    id: "4",
    name: "Taco Fiesta",
    description: "Authentic Mexican street food",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47",
    cuisine: ["Mexican", "Tacos"],
    rating: 4.7,
    deliveryFee: 2.0,
    minOrder: 12,
    isOpen: true,
    address: "321 Taco Street",
    menu: [
      {
        id: "4-1",
        name: "Street Tacos",
        description: "Three tacos with choice of meat",
        price: 9.99,
        category: "Tacos",
        image: "https://images.unsplash.com/photo-1613514785940-daed77c5f5fd",
        available: true,
      },
      {
        id: "4-2",
        name: "Burrito Supreme",
        description: "Large burrito with all toppings",
        price: 11.99,
        category: "Burritos",
        image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f",
        available: true,
      },
      {
        id: "4-3",
        name: "Quesadilla",
        description: "Cheese quesadilla with meat",
        price: 10.99,
        category: "Quesadillas",
        image: "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f",
        available: true,
      },
      {
        id: "4-4",
        name: "Nachos",
        description: "Loaded nachos with guacamole",
        price: 12.99,
        category: "Appetizers",
        image: "https://images.unsplash.com/photo-1582169296194-e4d644c48063",
        available: true,
      },
      {
        id: "4-5",
        name: "Churros",
        description: "Mexican pastry with chocolate",
        price: 5.99,
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1624371414361-e670edf4698d",
        available: true,
      },
    ],
  },
  {
    id: "5",
    name: "Thai Spice",
    description: "Authentic Thai cuisine",
    image: "https://images.unsplash.com/photo-1559314809-0d155014e29e",
    cuisine: ["Thai", "Asian"],
    rating: 4.4,
    deliveryFee: 3.0,
    minOrder: 20,
    isOpen: true,
    address: "567 Spice Road",
    menu: [
      {
        id: "5-1",
        name: "Pad Thai",
        description: "Classic rice noodle dish",
        price: 13.99,
        category: "Noodles",
        image: "https://images.unsplash.com/photo-1559314809-0d155014e29e",
        available: true,
      },
      {
        id: "5-2",
        name: "Green Curry",
        description: "Spicy coconut curry with chicken",
        price: 14.99,
        category: "Curry",
        image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd",
        available: true,
      },
      {
        id: "5-3",
        name: "Tom Yum Soup",
        description: "Spicy and sour soup",
        price: 11.99,
        category: "Soups",
        image: "https://images.unsplash.com/photo-1548943487-a2e4e43b4853",
        available: true,
      },
      {
        id: "5-4",
        name: "Spring Rolls",
        description: "Fresh vegetables rolls",
        price: 6.99,
        category: "Appetizers",
        image: "https://images.unsplash.com/photo-1544025162-d76694265947",
        available: true,
      },
      {
        id: "5-5",
        name: "Mango Sticky Rice",
        description: "Sweet sticky rice with fresh mango",
        price: 7.99,
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9",
        available: true,
      },
    ],
  },
  {
    id: "6",
    name: "Mediterranean Delight",
    description: "Fresh Mediterranean cuisine",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947",
    cuisine: ["Mediterranean", "Greek"],
    rating: 4.6,
    deliveryFee: 2.5,
    minOrder: 18,
    isOpen: true,
    address: "890 Med Ave",
    menu: [
      {
        id: "6-1",
        name: "Gyros Plate",
        description: "Sliced meat with pita and tzatziki",
        price: 15.99,
        category: "Main Dishes",
        image: "https://images.unsplash.com/photo-1529059997568-3d847b1154f0",
        available: true,
      },
      {
        id: "6-2",
        name: "Greek Salad",
        description: "Fresh vegetables with feta",
        price: 11.99,
        category: "Salads",
        image: "https://images.unsplash.com/photo-1522666257812-173fdc2d11fe",
        available: true,
      },
      {
        id: "6-3",
        name: "Hummus Plate",
        description: "Creamy hummus with pita",
        price: 8.99,
        category: "Appetizers",
        image: "https://images.unsplash.com/photo-1577906096429-f73c2c312435",
        available: true,
      },
      {
        id: "6-4",
        name: "Falafel Wrap",
        description: "Crispy falafel with vegetables",
        price: 12.99,
        category: "Wraps",
        image: "https://images.unsplash.com/photo-1593001874117-c99c800e3eb5",
        available: true,
      },
      {
        id: "6-5",
        name: "Baklava",
        description: "Sweet phyllo pastry dessert",
        price: 6.99,
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1519676867240-f03562e64548",
        available: true,
      },
    ],
  },
  {
    id: "7",
    name: "Indian Spices",
    description: "Traditional Indian cuisine",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe",
    cuisine: ["Indian", "Curry"],
    rating: 4.7,
    deliveryFee: 3.0,
    minOrder: 25,
    isOpen: true,
    address: "432 Curry Lane",
    menu: [
      {
        id: "7-1",
        name: "Butter Chicken",
        description: "Creamy tomato curry with chicken",
        price: 16.99,
        category: "Curry",
        image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398",
        available: true,
      },
      {
        id: "7-2",
        name: "Vegetable Biryani",
        description: "Fragrant rice with vegetables",
        price: 14.99,
        category: "Rice",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8",
        available: true,
      },
      {
        id: "7-3",
        name: "Garlic Naan",
        description: "Fresh bread with garlic",
        price: 3.99,
        category: "Bread",
        image: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e3",
        available: true,
      },
      {
        id: "7-4",
        name: "Samosas",
        description: "Crispy pastries with filling",
        price: 6.99,
        category: "Appetizers",
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
        available: true,
      },
      {
        id: "7-5",
        name: "Gulab Jamun",
        description: "Sweet milk dough balls",
        price: 5.99,
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1605197584547-c93bde544eb1",
        available: true,
      },
    ],
  },
  {
    id: "8",
    name: "Pho Express",
    description: "Vietnamese noodle soups and more",
    image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43",
    cuisine: ["Vietnamese", "Asian"],
    rating: 4.5,
    deliveryFee: 2.5,
    minOrder: 15,
    isOpen: true,
    address: "765 Noodle St",
    menu: [
      {
        id: "8-1",
        name: "Classic Pho",
        description: "Beef noodle soup",
        price: 12.99,
        category: "Soup",
        image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43",
        available: true,
      },
      {
        id: "8-2",
        name: "Banh Mi",
        description: "Vietnamese sandwich",
        price: 8.99,
        category: "Sandwiches",
        image: "https://images.unsplash.com/photo-1600454309261-3dc9b7e7fa7f",
        available: true,
      },
      {
        id: "8-3",
        name: "Spring Rolls",
        description: "Fresh rolls with peanut sauce",
        price: 6.99,
        category: "Appetizers",
        image: "https://images.unsplash.com/photo-1544025162-d76694265947",
        available: true,
      },
      {
        id: "8-4",
        name: "Rice Plate",
        description: "Grilled meat with rice",
        price: 13.99,
        category: "Rice Dishes",
        image: "https://images.unsplash.com/photo-1617622141573-2fa066b7d8fd",
        available: true,
      },
      {
        id: "8-5",
        name: "Vietnamese Coffee",
        description: "Strong coffee with condensed milk",
        price: 4.99,
        category: "Drinks",
        image: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9",
        available: true,
      },
    ],
  },
  {
    id: "9",
    name: "Healthy Bowl",
    description: "Fresh and healthy food bowls",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
    cuisine: ["Healthy", "Salads"],
    rating: 4.6,
    deliveryFee: 2.0,
    minOrder: 15,
    isOpen: true,
    address: "234 Green St",
    menu: [
      {
        id: "9-1",
        name: "Quinoa Bowl",
        description: "Quinoa with roasted vegetables",
        price: 13.99,
        category: "Bowls",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
        available: true,
      },
      {
        id: "9-2",
        name: "Acai Bowl",
        description: "Acai blend with fruits",
        price: 11.99,
        category: "Bowls",
        image: "https://images.unsplash.com/photo-1590301157890-4810ed352733",
        available: true,
      },
      {
        id: "9-3",
        name: "Green Smoothie",
        description: "Kale and fruit smoothie",
        price: 7.99,
        category: "Drinks",
        image: "https://images.unsplash.com/photo-1610970881699-44a5587cabec",
        available: true,
      },
      {
        id: "9-4",
        name: "Avocado Toast",
        description: "Whole grain toast with avocado",
        price: 9.99,
        category: "Toast",
        image: "https://images.unsplash.com/photo-1588137378633-dea1336ce1e2",
        available: true,
      },
      {
        id: "9-5",
        name: "Protein Box",
        description: "Assorted nuts and fruits",
        price: 8.99,
        category: "Snacks",
        image: "https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0",
        available: true,
      },
    ],
  },
  {
    id: "10",
    name: "BBQ King",
    description: "Authentic BBQ and smoked meats",
    image: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd",
    cuisine: ["BBQ", "American"],
    rating: 4.8,
    deliveryFee: 4.0,
    minOrder: 20,
    isOpen: true,
    address: "543 Smoke Rd",
    menu: [
      {
        id: "10-1",
        name: "Brisket Plate",
        description: "Smoked brisket with sides",
        price: 18.99,
        category: "Plates",
        image: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd",
        available: true,
      },
      {
        id: "10-2",
        name: "Pulled Pork Sandwich",
        description: "Tender pulled pork with slaw",
        price: 12.99,
        category: "Sandwiches",
        image: "https://images.unsplash.com/photo-1623653387945-2fd25214f8fc",
        available: true,
      },
      {
        id: "10-3",
        name: "Rack of Ribs",
        description: "Full rack with BBQ sauce",
        price: 24.99,
        category: "Plates",
        image: "https://images.unsplash.com/photo-1544025162-d76694265947",
        available: true,
      },
      {
        id: "10-4",
        name: "Mac and Cheese",
        description: "Creamy side dish",
        price: 6.99,
        category: "Sides",
        image: "https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7",
        available: true,
      },
      {
        id: "10-5",
        name: "Cornbread",
        description: "Sweet homemade cornbread",
        price: 4.99,
        category: "Sides",
        image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
        available: true,
      },
    ],
  },
];
